# Tensorflow Training: 
## Basic Commands



In [1]:
# Import libraries

import tensorflow as tf
import numpy as np

_____
# How to represent vectors and matrix

In [2]:
# A vector
v1 = [1, 2, 3]
v2 = [4, 5, 6]

v1

[1, 2, 3]

In [3]:
# A Matrix is represented as a set of vectors, where each vector is a row

m1 = [v1,
      v2]
m1

[[1, 2, 3], [4, 5, 6]]

In [4]:
# Or using numpy

m2 = np.array([v1, v2], dtype=np.float32)
m2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [5]:
# Using Tensorflow
m3 = tf.constant([[1.0, 2.0],
                  [3.0, 4.0]])

2022-09-21 01:21:58.473534: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-21 01:21:58.474291: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 4. Tune using inter_op_parallelism_threads for best performance.


In [6]:
print(m1)
print(m2)
print(m3)

[[1, 2, 3], [4, 5, 6]]
[[1. 2. 3.]
 [4. 5. 6.]]
tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [7]:
# Creates tensor objects from the various types

t1 = tf.convert_to_tensor(m1, dtype=tf.float32)
t2 = tf.convert_to_tensor(m2, dtype=tf.float32)
t3 = tf.convert_to_tensor(m3, dtype=tf.float32)

In [8]:
print(type(t1))
print(type(t2))
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


## Tensors of Different Dimensions

In [9]:
# Defines a 2 × 1 matrix of rank 2

m1 = tf.constant([[1., 2.]])

In [10]:
# Defines a 1 × 2 matrix of rank 2

m2 = tf.constant([[1], [2]])

In [11]:
# Defines a rank-3 tensor

m3 = tf.constant([ [[1,2],
                    [3,4],
                    [5,6]],
                    [[7,8],
                    [9,10],
                    [11,12]] ])

In [12]:
print(m1)
print(m2)
print(m3)

tf.Tensor([[1. 2.]], shape=(1, 2), dtype=float32)
tf.Tensor(
[[1]
 [2]], shape=(2, 1), dtype=int32)
tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32)


In [13]:
# How to access the elements inside the tensor

m3[0][0][1]

<tf.Tensor: id=17, shape=(), dtype=int32, numpy=2>

In [14]:
# Operators

x = tf.constant([[1, 2]])
negMatrix = tf.negative(x)
print(negMatrix)

tf.Tensor([[-1 -2]], shape=(1, 2), dtype=int32)


In [40]:
# Gaussian Distribution with Tensorflow

from math import pi
mean = 0.0
sigma = 1.0
for x in [0, 0.5, 1, 1.5, 2]:
    print(x)
    print((tf.exp(tf.negative(tf.pow(x - mean, 2.0) / (2.0 * tf.pow(sigma, 2.0) ))) * (1.0 / (sigma * tf.sqrt(2.0 * pi) ))).numpy())

0
0.3989423
0.5
0.35206532
1
0.24197073
1.5
0.1295176
2
0.053990968
